name: Code Quality Checks

on:
  push:
    branches: ["main"]
  pull_request:

# Kill existing jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-autopep8-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-autopep8
      - run: |
          python -m pip install --upgrade pip
          pip install autopep8 isort
      - run: autopep8 --diff --exit-code $(git ls-files '*.py')
      - run: isort --diff --check $(git ls-files '*.py')

  run-unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -c "import sys; print(sys.version)"
      - run: |
          python -m pip install --upgrade pip
          pip install --editable .
      - run: python -m unittest
